const categoriesIconMap = new Map()
  .set(69, 'plus-hexagon')
  .set(72, 'heartbeat')
  .set(73, 'piggy-bank')
  .set(74, 'users')
  .set(75, 'business-time')
  .set(76, 'star-christmas')
  .set(77, 'venus-mars')
  .set(78, 'theater-masks')
  .set(79, 'utensils')
  .set(80, 'language')
  .set(81, 'gavel')
  .set(82, 'download')
  .set(83, 'book')
  .set(84, 'building')
  .set(85, 'user-chart')
  .set(86, 'lips')
  .set(87, 'leaf')
  .set(88, 'user-graduate')
  .set(89, 'swimmer')
  .set(90, 'pencil-ruler')
  .set(91, 'globe')
  .set(92, 'hand-holding-seedling')
  .set(93, 'music')
  .set(94, 'laptop-code')
  .set(97, 'laptop-house')

const getCategoryIconById = id => categoriesIconMap.get(id)

export { getCategoryIconById }
